// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewUserSite.Data;

#nullable disable

namespace NewUserSite.Migrations
{
    [DbContext(typeof(NewUserDbContext))]
    [Migration("20260709144409_ApplicationPreferences")]
    partial class ApplicationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ADOrganizationalUnitNewUserTemplate", b =>
                {
                    b.Property<int>("ADOrganizationalUnitsId")
                        .HasColumnType("int");

                    b.Property<int>("NewUserTemplatesId")
                        .HasColumnType("int");

                    b.HasKey("ADOrganizationalUnitsId", "NewUserTemplatesId");

                    b.HasIndex("NewUserTemplatesId");

                    b.ToTable("ADOrganizationalUnitNewUserTemplate");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("NewUserSite.Models.ADOrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ADDistinguishedName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADOrganizationalUnits");
                });

            modelBuilder.Entity("NewUserSite.Models.ADSearcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DomainControllerLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("DomainControllerRoot")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateOU")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADSearchers");
                });

            modelBuilder.Entity("NewUserSite.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("NewUserSite.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("NewUserSite.Models.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ADOrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DomainId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("NewUserTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorEmail")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ADOrganizationalUnitId");

                    b.HasIndex("DomainId");

                    b.HasIndex("NewUserTemplateId");

                    b.ToTable("NewUsers");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUserTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateSAMAccountName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NewUserTemplates");
                });

            modelBuilder.Entity("NewUserSite.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationSubject")
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ADOrganizationalUnitNewUserTemplate", b =>
                {
                    b.HasOne("NewUserSite.Models.ADOrganizationalUnit", null)
                        .WithMany()
                        .HasForeignKey("ADOrganizationalUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewUserSite.Models.NewUserTemplate", null)
                        .WithMany()
                        .HasForeignKey("NewUserTemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewUserSite.Models.AppUser", b =>
                {
                    b.HasOne("NewUserSite.Models.Notification", null)
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("NotificationId");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUser", b =>
                {
                    b.HasOne("NewUserSite.Models.ADOrganizationalUnit", "ADOrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("ADOrganizationalUnitId");

                    b.HasOne("NewUserSite.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.HasOne("NewUserSite.Models.NewUserTemplate", "NewUserTemplate")
                        .WithMany()
                        .HasForeignKey("NewUserTemplateId");

                    b.Navigation("ADOrganizationalUnit");

                    b.Navigation("Domain");

                    b.Navigation("NewUserTemplate");
                });

            modelBuilder.Entity("NewUserSite.Models.Notification", b =>
                {
                    b.Navigation("NotificationRecipients");
                });
#pragma warning restore 612, 618
        }
    }
}
