// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewUserSite.Data;

#nullable disable

namespace NewUserSite.Migrations
{
    [DbContext(typeof(NewUserDbContext))]
    partial class NewUserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NewUserSite.Models.ADOrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ADDistinguishedName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ADOrganizationalUnit");
                });

            modelBuilder.Entity("NewUserSite.Models.ADSearcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DomainControllerLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("DomainControllerRoot")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateOU")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AdSearchers");
                });

            modelBuilder.Entity("NewUserSite.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdOrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("NewUserTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorEmail")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdOrganizationalUnitId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NewUserTemplateId");

                    b.ToTable("NewUsers");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUserTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ADOrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateSAMAccountName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ADOrganizationalUnitId");

                    b.ToTable("NewUserTemplate");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUser", b =>
                {
                    b.HasOne("NewUserSite.Models.ADOrganizationalUnit", "AdOrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("AdOrganizationalUnitId");

                    b.HasOne("NewUserSite.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("NewUserSite.Models.NewUserTemplate", "NewUserTemplate")
                        .WithMany()
                        .HasForeignKey("NewUserTemplateId");

                    b.Navigation("AdOrganizationalUnit");

                    b.Navigation("CreatedBy");

                    b.Navigation("NewUserTemplate");
                });

            modelBuilder.Entity("NewUserSite.Models.NewUserTemplate", b =>
                {
                    b.HasOne("NewUserSite.Models.ADOrganizationalUnit", null)
                        .WithMany("NewUserTemplates")
                        .HasForeignKey("ADOrganizationalUnitId");
                });

            modelBuilder.Entity("NewUserSite.Models.ADOrganizationalUnit", b =>
                {
                    b.Navigation("NewUserTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
